apiVersion: v1
kind: Deployment
metadata:
name: aplicacao
spec:
replicas: 1
containers:
- name: container-aplicacao
  image: dockerfile
  imagePullPolicy: Always
  ports:
    - containerPort: 5000